services:
  static:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ${UPLOAD_FOLDER}:/usr/share/nginx/html/pictures
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    environment:
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
